/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedGuruRouteImport } from './routes/_authenticated/guru'
import { Route as AuthenticatedAdvisorsRouteImport } from './routes/_authenticated/advisors'
import { Route as AuthenticatedScheduleIndexRouteImport } from './routes/_authenticated/schedule/index'
import { Route as AuthenticatedEssaysIndexRouteImport } from './routes/_authenticated/essays/index'
import { Route as AuthenticatedStudentsUserIdRouteImport } from './routes/_authenticated/students/$userId'
import { Route as AuthenticatedStudentUniversitiesRouteImport } from './routes/_authenticated/student/universities'
import { Route as AuthenticatedStudentSessionsRouteImport } from './routes/_authenticated/student/sessions'
import { Route as AuthenticatedStudentProfileRouteImport } from './routes/_authenticated/student/profile'
import { Route as AuthenticatedStudentDashboardRouteImport } from './routes/_authenticated/student/dashboard'
import { Route as AuthenticatedStudentUserIdRouteImport } from './routes/_authenticated/student/$userId'
import { Route as AuthenticatedSessionsSessionIdRouteImport } from './routes/_authenticated/sessions/$sessionId'
import { Route as AuthenticatedSessionsAutoSessionIdRouteImport } from './routes/_authenticated/sessions/$autoSessionId'
import { Route as AuthenticatedEssaysEssayIdRouteImport } from './routes/_authenticated/essays/$essayId'
import { Route as AuthenticatedAdvisorsUserIdRouteImport } from './routes/_authenticated/advisors/$userId'
import { Route as AuthenticatedStudentUniversitiesIndexRouteImport } from './routes/_authenticated/student/universities.index'
import { Route as AuthenticatedStudentAptitudeIndexRouteImport } from './routes/_authenticated/student/aptitude/index'
import { Route as AuthenticatedStudentUniversitiesShortlistRouteImport } from './routes/_authenticated/student/universities.shortlist'
import { Route as AuthenticatedStudentUniversitiesExplorerRouteImport } from './routes/_authenticated/student/universities.explorer'
import { Route as AuthenticatedStudentSessionsSessionIdRouteImport } from './routes/_authenticated/student/sessions/$sessionId'
import { Route as AuthenticatedStudentAptitudeSessionIdRouteImport } from './routes/_authenticated/student/aptitude/$sessionId'
import { Route as AuthenticatedSessionsUserSessionIdRouteImport } from './routes/_authenticated/sessions/user/$sessionId'
import { Route as AuthenticatedStudentUniversitiesCountryIdRouteImport } from './routes/_authenticated/student/universities.$country.$id'
import { ServerRoute as ApiGoogle_oauth_callbackServerRouteImport } from './routes/api/google_oauth_callback'
import { ServerRoute as ApiRpcSplatServerRouteImport } from './routes/api/rpc.$'
import { ServerRoute as ApiAuthLoginServerRouteImport } from './routes/api/auth/login'
import { ServerRoute as ApiAuthCallbackServerRouteImport } from './routes/api/auth/callback'

const rootServerRouteImport = createServerRootRoute()

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuruRoute = AuthenticatedGuruRouteImport.update({
  id: '/guru',
  path: '/guru',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdvisorsRoute = AuthenticatedAdvisorsRouteImport.update({
  id: '/advisors',
  path: '/advisors',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScheduleIndexRoute =
  AuthenticatedScheduleIndexRouteImport.update({
    id: '/schedule/',
    path: '/schedule/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEssaysIndexRoute =
  AuthenticatedEssaysIndexRouteImport.update({
    id: '/essays/',
    path: '/essays/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentsUserIdRoute =
  AuthenticatedStudentsUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any)
const AuthenticatedStudentUniversitiesRoute =
  AuthenticatedStudentUniversitiesRouteImport.update({
    id: '/student/universities',
    path: '/student/universities',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentSessionsRoute =
  AuthenticatedStudentSessionsRouteImport.update({
    id: '/student/sessions',
    path: '/student/sessions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentProfileRoute =
  AuthenticatedStudentProfileRouteImport.update({
    id: '/student/profile',
    path: '/student/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentDashboardRoute =
  AuthenticatedStudentDashboardRouteImport.update({
    id: '/student/dashboard',
    path: '/student/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentUserIdRoute =
  AuthenticatedStudentUserIdRouteImport.update({
    id: '/student/$userId',
    path: '/student/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSessionsSessionIdRoute =
  AuthenticatedSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedSessionsRoute,
  } as any)
const AuthenticatedSessionsAutoSessionIdRoute =
  AuthenticatedSessionsAutoSessionIdRouteImport.update({
    id: '/$autoSessionId',
    path: '/$autoSessionId',
    getParentRoute: () => AuthenticatedSessionsRoute,
  } as any)
const AuthenticatedEssaysEssayIdRoute =
  AuthenticatedEssaysEssayIdRouteImport.update({
    id: '/essays/$essayId',
    path: '/essays/$essayId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdvisorsUserIdRoute =
  AuthenticatedAdvisorsUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedAdvisorsRoute,
  } as any)
const AuthenticatedStudentUniversitiesIndexRoute =
  AuthenticatedStudentUniversitiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentUniversitiesRoute,
  } as any)
const AuthenticatedStudentAptitudeIndexRoute =
  AuthenticatedStudentAptitudeIndexRouteImport.update({
    id: '/student/aptitude/',
    path: '/student/aptitude/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentUniversitiesShortlistRoute =
  AuthenticatedStudentUniversitiesShortlistRouteImport.update({
    id: '/shortlist',
    path: '/shortlist',
    getParentRoute: () => AuthenticatedStudentUniversitiesRoute,
  } as any)
const AuthenticatedStudentUniversitiesExplorerRoute =
  AuthenticatedStudentUniversitiesExplorerRouteImport.update({
    id: '/explorer',
    path: '/explorer',
    getParentRoute: () => AuthenticatedStudentUniversitiesRoute,
  } as any)
const AuthenticatedStudentSessionsSessionIdRoute =
  AuthenticatedStudentSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedStudentSessionsRoute,
  } as any)
const AuthenticatedStudentAptitudeSessionIdRoute =
  AuthenticatedStudentAptitudeSessionIdRouteImport.update({
    id: '/student/aptitude/$sessionId',
    path: '/student/aptitude/$sessionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSessionsUserSessionIdRoute =
  AuthenticatedSessionsUserSessionIdRouteImport.update({
    id: '/user/$sessionId',
    path: '/user/$sessionId',
    getParentRoute: () => AuthenticatedSessionsRoute,
  } as any)
const AuthenticatedStudentUniversitiesCountryIdRoute =
  AuthenticatedStudentUniversitiesCountryIdRouteImport.update({
    id: '/$country/$id',
    path: '/$country/$id',
    getParentRoute: () => AuthenticatedStudentUniversitiesRoute,
  } as any)
const ApiGoogle_oauth_callbackServerRoute =
  ApiGoogle_oauth_callbackServerRouteImport.update({
    id: '/api/google_oauth_callback',
    path: '/api/google_oauth_callback',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiRpcSplatServerRoute = ApiRpcSplatServerRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthLoginServerRoute = ApiAuthLoginServerRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthCallbackServerRoute = ApiAuthCallbackServerRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisors': typeof AuthenticatedAdvisorsRouteWithChildren
  '/guru': typeof AuthenticatedGuruRoute
  '/home': typeof AuthenticatedHomeRoute
  '/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/advisors/$userId': typeof AuthenticatedAdvisorsUserIdRoute
  '/essays/$essayId': typeof AuthenticatedEssaysEssayIdRoute
  '/sessions/$autoSessionId': typeof AuthenticatedSessionsAutoSessionIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/student/$userId': typeof AuthenticatedStudentUserIdRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/student/sessions': typeof AuthenticatedStudentSessionsRouteWithChildren
  '/student/universities': typeof AuthenticatedStudentUniversitiesRouteWithChildren
  '/students/$userId': typeof AuthenticatedStudentsUserIdRoute
  '/essays': typeof AuthenticatedEssaysIndexRoute
  '/schedule': typeof AuthenticatedScheduleIndexRoute
  '/sessions/user/$sessionId': typeof AuthenticatedSessionsUserSessionIdRoute
  '/student/aptitude/$sessionId': typeof AuthenticatedStudentAptitudeSessionIdRoute
  '/student/sessions/$sessionId': typeof AuthenticatedStudentSessionsSessionIdRoute
  '/student/universities/explorer': typeof AuthenticatedStudentUniversitiesExplorerRoute
  '/student/universities/shortlist': typeof AuthenticatedStudentUniversitiesShortlistRoute
  '/student/aptitude': typeof AuthenticatedStudentAptitudeIndexRoute
  '/student/universities/': typeof AuthenticatedStudentUniversitiesIndexRoute
  '/student/universities/$country/$id': typeof AuthenticatedStudentUniversitiesCountryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisors': typeof AuthenticatedAdvisorsRouteWithChildren
  '/guru': typeof AuthenticatedGuruRoute
  '/home': typeof AuthenticatedHomeRoute
  '/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/advisors/$userId': typeof AuthenticatedAdvisorsUserIdRoute
  '/essays/$essayId': typeof AuthenticatedEssaysEssayIdRoute
  '/sessions/$autoSessionId': typeof AuthenticatedSessionsAutoSessionIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/student/$userId': typeof AuthenticatedStudentUserIdRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/student/sessions': typeof AuthenticatedStudentSessionsRouteWithChildren
  '/students/$userId': typeof AuthenticatedStudentsUserIdRoute
  '/essays': typeof AuthenticatedEssaysIndexRoute
  '/schedule': typeof AuthenticatedScheduleIndexRoute
  '/sessions/user/$sessionId': typeof AuthenticatedSessionsUserSessionIdRoute
  '/student/aptitude/$sessionId': typeof AuthenticatedStudentAptitudeSessionIdRoute
  '/student/sessions/$sessionId': typeof AuthenticatedStudentSessionsSessionIdRoute
  '/student/universities/explorer': typeof AuthenticatedStudentUniversitiesExplorerRoute
  '/student/universities/shortlist': typeof AuthenticatedStudentUniversitiesShortlistRoute
  '/student/aptitude': typeof AuthenticatedStudentAptitudeIndexRoute
  '/student/universities': typeof AuthenticatedStudentUniversitiesIndexRoute
  '/student/universities/$country/$id': typeof AuthenticatedStudentUniversitiesCountryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/advisors': typeof AuthenticatedAdvisorsRouteWithChildren
  '/_authenticated/guru': typeof AuthenticatedGuruRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/advisors/$userId': typeof AuthenticatedAdvisorsUserIdRoute
  '/_authenticated/essays/$essayId': typeof AuthenticatedEssaysEssayIdRoute
  '/_authenticated/sessions/$autoSessionId': typeof AuthenticatedSessionsAutoSessionIdRoute
  '/_authenticated/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/_authenticated/student/$userId': typeof AuthenticatedStudentUserIdRoute
  '/_authenticated/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/_authenticated/student/profile': typeof AuthenticatedStudentProfileRoute
  '/_authenticated/student/sessions': typeof AuthenticatedStudentSessionsRouteWithChildren
  '/_authenticated/student/universities': typeof AuthenticatedStudentUniversitiesRouteWithChildren
  '/_authenticated/students/$userId': typeof AuthenticatedStudentsUserIdRoute
  '/_authenticated/essays/': typeof AuthenticatedEssaysIndexRoute
  '/_authenticated/schedule/': typeof AuthenticatedScheduleIndexRoute
  '/_authenticated/sessions/user/$sessionId': typeof AuthenticatedSessionsUserSessionIdRoute
  '/_authenticated/student/aptitude/$sessionId': typeof AuthenticatedStudentAptitudeSessionIdRoute
  '/_authenticated/student/sessions/$sessionId': typeof AuthenticatedStudentSessionsSessionIdRoute
  '/_authenticated/student/universities/explorer': typeof AuthenticatedStudentUniversitiesExplorerRoute
  '/_authenticated/student/universities/shortlist': typeof AuthenticatedStudentUniversitiesShortlistRoute
  '/_authenticated/student/aptitude/': typeof AuthenticatedStudentAptitudeIndexRoute
  '/_authenticated/student/universities/': typeof AuthenticatedStudentUniversitiesIndexRoute
  '/_authenticated/student/universities/$country/$id': typeof AuthenticatedStudentUniversitiesCountryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisors'
    | '/guru'
    | '/home'
    | '/sessions'
    | '/students'
    | '/users'
    | '/advisors/$userId'
    | '/essays/$essayId'
    | '/sessions/$autoSessionId'
    | '/sessions/$sessionId'
    | '/student/$userId'
    | '/student/dashboard'
    | '/student/profile'
    | '/student/sessions'
    | '/student/universities'
    | '/students/$userId'
    | '/essays'
    | '/schedule'
    | '/sessions/user/$sessionId'
    | '/student/aptitude/$sessionId'
    | '/student/sessions/$sessionId'
    | '/student/universities/explorer'
    | '/student/universities/shortlist'
    | '/student/aptitude'
    | '/student/universities/'
    | '/student/universities/$country/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisors'
    | '/guru'
    | '/home'
    | '/sessions'
    | '/students'
    | '/users'
    | '/advisors/$userId'
    | '/essays/$essayId'
    | '/sessions/$autoSessionId'
    | '/sessions/$sessionId'
    | '/student/$userId'
    | '/student/dashboard'
    | '/student/profile'
    | '/student/sessions'
    | '/students/$userId'
    | '/essays'
    | '/schedule'
    | '/sessions/user/$sessionId'
    | '/student/aptitude/$sessionId'
    | '/student/sessions/$sessionId'
    | '/student/universities/explorer'
    | '/student/universities/shortlist'
    | '/student/aptitude'
    | '/student/universities'
    | '/student/universities/$country/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/advisors'
    | '/_authenticated/guru'
    | '/_authenticated/home'
    | '/_authenticated/sessions'
    | '/_authenticated/students'
    | '/_authenticated/users'
    | '/_authenticated/advisors/$userId'
    | '/_authenticated/essays/$essayId'
    | '/_authenticated/sessions/$autoSessionId'
    | '/_authenticated/sessions/$sessionId'
    | '/_authenticated/student/$userId'
    | '/_authenticated/student/dashboard'
    | '/_authenticated/student/profile'
    | '/_authenticated/student/sessions'
    | '/_authenticated/student/universities'
    | '/_authenticated/students/$userId'
    | '/_authenticated/essays/'
    | '/_authenticated/schedule/'
    | '/_authenticated/sessions/user/$sessionId'
    | '/_authenticated/student/aptitude/$sessionId'
    | '/_authenticated/student/sessions/$sessionId'
    | '/_authenticated/student/universities/explorer'
    | '/_authenticated/student/universities/shortlist'
    | '/_authenticated/student/aptitude/'
    | '/_authenticated/student/universities/'
    | '/_authenticated/student/universities/$country/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/google_oauth_callback': typeof ApiGoogle_oauth_callbackServerRoute
  '/api/auth/callback': typeof ApiAuthCallbackServerRoute
  '/api/auth/login': typeof ApiAuthLoginServerRoute
  '/api/rpc/$': typeof ApiRpcSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/google_oauth_callback': typeof ApiGoogle_oauth_callbackServerRoute
  '/api/auth/callback': typeof ApiAuthCallbackServerRoute
  '/api/auth/login': typeof ApiAuthLoginServerRoute
  '/api/rpc/$': typeof ApiRpcSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/google_oauth_callback': typeof ApiGoogle_oauth_callbackServerRoute
  '/api/auth/callback': typeof ApiAuthCallbackServerRoute
  '/api/auth/login': typeof ApiAuthLoginServerRoute
  '/api/rpc/$': typeof ApiRpcSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/google_oauth_callback'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/rpc/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/api/google_oauth_callback'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/api/google_oauth_callback'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/rpc/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiGoogle_oauth_callbackServerRoute: typeof ApiGoogle_oauth_callbackServerRoute
  ApiAuthCallbackServerRoute: typeof ApiAuthCallbackServerRoute
  ApiAuthLoginServerRoute: typeof ApiAuthLoginServerRoute
  ApiRpcSplatServerRoute: typeof ApiRpcSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guru': {
      id: '/_authenticated/guru'
      path: '/guru'
      fullPath: '/guru'
      preLoaderRoute: typeof AuthenticatedGuruRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/advisors': {
      id: '/_authenticated/advisors'
      path: '/advisors'
      fullPath: '/advisors'
      preLoaderRoute: typeof AuthenticatedAdvisorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedule/': {
      id: '/_authenticated/schedule/'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/essays/': {
      id: '/_authenticated/essays/'
      path: '/essays'
      fullPath: '/essays'
      preLoaderRoute: typeof AuthenticatedEssaysIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students/$userId': {
      id: '/_authenticated/students/$userId'
      path: '/$userId'
      fullPath: '/students/$userId'
      preLoaderRoute: typeof AuthenticatedStudentsUserIdRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/student/universities': {
      id: '/_authenticated/student/universities'
      path: '/student/universities'
      fullPath: '/student/universities'
      preLoaderRoute: typeof AuthenticatedStudentUniversitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/sessions': {
      id: '/_authenticated/student/sessions'
      path: '/student/sessions'
      fullPath: '/student/sessions'
      preLoaderRoute: typeof AuthenticatedStudentSessionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/profile': {
      id: '/_authenticated/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof AuthenticatedStudentProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/dashboard': {
      id: '/_authenticated/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof AuthenticatedStudentDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/$userId': {
      id: '/_authenticated/student/$userId'
      path: '/student/$userId'
      fullPath: '/student/$userId'
      preLoaderRoute: typeof AuthenticatedStudentUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions/$sessionId': {
      id: '/_authenticated/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/_authenticated/sessions/$autoSessionId': {
      id: '/_authenticated/sessions/$autoSessionId'
      path: '/$autoSessionId'
      fullPath: '/sessions/$autoSessionId'
      preLoaderRoute: typeof AuthenticatedSessionsAutoSessionIdRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/_authenticated/essays/$essayId': {
      id: '/_authenticated/essays/$essayId'
      path: '/essays/$essayId'
      fullPath: '/essays/$essayId'
      preLoaderRoute: typeof AuthenticatedEssaysEssayIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/advisors/$userId': {
      id: '/_authenticated/advisors/$userId'
      path: '/$userId'
      fullPath: '/advisors/$userId'
      preLoaderRoute: typeof AuthenticatedAdvisorsUserIdRouteImport
      parentRoute: typeof AuthenticatedAdvisorsRoute
    }
    '/_authenticated/student/universities/': {
      id: '/_authenticated/student/universities/'
      path: '/'
      fullPath: '/student/universities/'
      preLoaderRoute: typeof AuthenticatedStudentUniversitiesIndexRouteImport
      parentRoute: typeof AuthenticatedStudentUniversitiesRoute
    }
    '/_authenticated/student/aptitude/': {
      id: '/_authenticated/student/aptitude/'
      path: '/student/aptitude'
      fullPath: '/student/aptitude'
      preLoaderRoute: typeof AuthenticatedStudentAptitudeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/universities/shortlist': {
      id: '/_authenticated/student/universities/shortlist'
      path: '/shortlist'
      fullPath: '/student/universities/shortlist'
      preLoaderRoute: typeof AuthenticatedStudentUniversitiesShortlistRouteImport
      parentRoute: typeof AuthenticatedStudentUniversitiesRoute
    }
    '/_authenticated/student/universities/explorer': {
      id: '/_authenticated/student/universities/explorer'
      path: '/explorer'
      fullPath: '/student/universities/explorer'
      preLoaderRoute: typeof AuthenticatedStudentUniversitiesExplorerRouteImport
      parentRoute: typeof AuthenticatedStudentUniversitiesRoute
    }
    '/_authenticated/student/sessions/$sessionId': {
      id: '/_authenticated/student/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/student/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedStudentSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedStudentSessionsRoute
    }
    '/_authenticated/student/aptitude/$sessionId': {
      id: '/_authenticated/student/aptitude/$sessionId'
      path: '/student/aptitude/$sessionId'
      fullPath: '/student/aptitude/$sessionId'
      preLoaderRoute: typeof AuthenticatedStudentAptitudeSessionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions/user/$sessionId': {
      id: '/_authenticated/sessions/user/$sessionId'
      path: '/user/$sessionId'
      fullPath: '/sessions/user/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionsUserSessionIdRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/_authenticated/student/universities/$country/$id': {
      id: '/_authenticated/student/universities/$country/$id'
      path: '/$country/$id'
      fullPath: '/student/universities/$country/$id'
      preLoaderRoute: typeof AuthenticatedStudentUniversitiesCountryIdRouteImport
      parentRoute: typeof AuthenticatedStudentUniversitiesRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/google_oauth_callback': {
      id: '/api/google_oauth_callback'
      path: '/api/google_oauth_callback'
      fullPath: '/api/google_oauth_callback'
      preLoaderRoute: typeof ApiGoogle_oauth_callbackServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AuthenticatedAdvisorsRouteChildren {
  AuthenticatedAdvisorsUserIdRoute: typeof AuthenticatedAdvisorsUserIdRoute
}

const AuthenticatedAdvisorsRouteChildren: AuthenticatedAdvisorsRouteChildren = {
  AuthenticatedAdvisorsUserIdRoute: AuthenticatedAdvisorsUserIdRoute,
}

const AuthenticatedAdvisorsRouteWithChildren =
  AuthenticatedAdvisorsRoute._addFileChildren(
    AuthenticatedAdvisorsRouteChildren,
  )

interface AuthenticatedSessionsRouteChildren {
  AuthenticatedSessionsAutoSessionIdRoute: typeof AuthenticatedSessionsAutoSessionIdRoute
  AuthenticatedSessionsSessionIdRoute: typeof AuthenticatedSessionsSessionIdRoute
  AuthenticatedSessionsUserSessionIdRoute: typeof AuthenticatedSessionsUserSessionIdRoute
}

const AuthenticatedSessionsRouteChildren: AuthenticatedSessionsRouteChildren = {
  AuthenticatedSessionsAutoSessionIdRoute:
    AuthenticatedSessionsAutoSessionIdRoute,
  AuthenticatedSessionsSessionIdRoute: AuthenticatedSessionsSessionIdRoute,
  AuthenticatedSessionsUserSessionIdRoute:
    AuthenticatedSessionsUserSessionIdRoute,
}

const AuthenticatedSessionsRouteWithChildren =
  AuthenticatedSessionsRoute._addFileChildren(
    AuthenticatedSessionsRouteChildren,
  )

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsUserIdRoute: typeof AuthenticatedStudentsUserIdRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsUserIdRoute: AuthenticatedStudentsUserIdRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedStudentSessionsRouteChildren {
  AuthenticatedStudentSessionsSessionIdRoute: typeof AuthenticatedStudentSessionsSessionIdRoute
}

const AuthenticatedStudentSessionsRouteChildren: AuthenticatedStudentSessionsRouteChildren =
  {
    AuthenticatedStudentSessionsSessionIdRoute:
      AuthenticatedStudentSessionsSessionIdRoute,
  }

const AuthenticatedStudentSessionsRouteWithChildren =
  AuthenticatedStudentSessionsRoute._addFileChildren(
    AuthenticatedStudentSessionsRouteChildren,
  )

interface AuthenticatedStudentUniversitiesRouteChildren {
  AuthenticatedStudentUniversitiesExplorerRoute: typeof AuthenticatedStudentUniversitiesExplorerRoute
  AuthenticatedStudentUniversitiesShortlistRoute: typeof AuthenticatedStudentUniversitiesShortlistRoute
  AuthenticatedStudentUniversitiesIndexRoute: typeof AuthenticatedStudentUniversitiesIndexRoute
  AuthenticatedStudentUniversitiesCountryIdRoute: typeof AuthenticatedStudentUniversitiesCountryIdRoute
}

const AuthenticatedStudentUniversitiesRouteChildren: AuthenticatedStudentUniversitiesRouteChildren =
  {
    AuthenticatedStudentUniversitiesExplorerRoute:
      AuthenticatedStudentUniversitiesExplorerRoute,
    AuthenticatedStudentUniversitiesShortlistRoute:
      AuthenticatedStudentUniversitiesShortlistRoute,
    AuthenticatedStudentUniversitiesIndexRoute:
      AuthenticatedStudentUniversitiesIndexRoute,
    AuthenticatedStudentUniversitiesCountryIdRoute:
      AuthenticatedStudentUniversitiesCountryIdRoute,
  }

const AuthenticatedStudentUniversitiesRouteWithChildren =
  AuthenticatedStudentUniversitiesRoute._addFileChildren(
    AuthenticatedStudentUniversitiesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdvisorsRoute: typeof AuthenticatedAdvisorsRouteWithChildren
  AuthenticatedGuruRoute: typeof AuthenticatedGuruRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRouteWithChildren
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedEssaysEssayIdRoute: typeof AuthenticatedEssaysEssayIdRoute
  AuthenticatedStudentUserIdRoute: typeof AuthenticatedStudentUserIdRoute
  AuthenticatedStudentDashboardRoute: typeof AuthenticatedStudentDashboardRoute
  AuthenticatedStudentProfileRoute: typeof AuthenticatedStudentProfileRoute
  AuthenticatedStudentSessionsRoute: typeof AuthenticatedStudentSessionsRouteWithChildren
  AuthenticatedStudentUniversitiesRoute: typeof AuthenticatedStudentUniversitiesRouteWithChildren
  AuthenticatedEssaysIndexRoute: typeof AuthenticatedEssaysIndexRoute
  AuthenticatedScheduleIndexRoute: typeof AuthenticatedScheduleIndexRoute
  AuthenticatedStudentAptitudeSessionIdRoute: typeof AuthenticatedStudentAptitudeSessionIdRoute
  AuthenticatedStudentAptitudeIndexRoute: typeof AuthenticatedStudentAptitudeIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdvisorsRoute: AuthenticatedAdvisorsRouteWithChildren,
  AuthenticatedGuruRoute: AuthenticatedGuruRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRouteWithChildren,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedEssaysEssayIdRoute: AuthenticatedEssaysEssayIdRoute,
  AuthenticatedStudentUserIdRoute: AuthenticatedStudentUserIdRoute,
  AuthenticatedStudentDashboardRoute: AuthenticatedStudentDashboardRoute,
  AuthenticatedStudentProfileRoute: AuthenticatedStudentProfileRoute,
  AuthenticatedStudentSessionsRoute:
    AuthenticatedStudentSessionsRouteWithChildren,
  AuthenticatedStudentUniversitiesRoute:
    AuthenticatedStudentUniversitiesRouteWithChildren,
  AuthenticatedEssaysIndexRoute: AuthenticatedEssaysIndexRoute,
  AuthenticatedScheduleIndexRoute: AuthenticatedScheduleIndexRoute,
  AuthenticatedStudentAptitudeSessionIdRoute:
    AuthenticatedStudentAptitudeSessionIdRoute,
  AuthenticatedStudentAptitudeIndexRoute:
    AuthenticatedStudentAptitudeIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiGoogle_oauth_callbackServerRoute: ApiGoogle_oauth_callbackServerRoute,
  ApiAuthCallbackServerRoute: ApiAuthCallbackServerRoute,
  ApiAuthLoginServerRoute: ApiAuthLoginServerRoute,
  ApiRpcSplatServerRoute: ApiRpcSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
