/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuruRouteImport } from './routes/guru'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuruChatSessionIdRouteImport } from './routes/guru/$chatSessionId'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'

const GuruRoute = GuruRouteImport.update({
  id: '/guru',
  path: '/guru',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuruChatSessionIdRoute = GuruChatSessionIdRouteImport.update({
  id: '/$chatSessionId',
  path: '/$chatSessionId',
  getParentRoute: () => GuruRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guru': typeof GuruRouteWithChildren
  '/guru/$chatSessionId': typeof GuruChatSessionIdRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guru': typeof GuruRouteWithChildren
  '/guru/$chatSessionId': typeof GuruChatSessionIdRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guru': typeof GuruRouteWithChildren
  '/guru/$chatSessionId': typeof GuruChatSessionIdRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guru' | '/guru/$chatSessionId' | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guru' | '/guru/$chatSessionId' | '/api/rpc/$'
  id: '__root__' | '/' | '/guru' | '/guru/$chatSessionId' | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuruRoute: typeof GuruRouteWithChildren
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guru': {
      id: '/guru'
      path: '/guru'
      fullPath: '/guru'
      preLoaderRoute: typeof GuruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guru/$chatSessionId': {
      id: '/guru/$chatSessionId'
      path: '/$chatSessionId'
      fullPath: '/guru/$chatSessionId'
      preLoaderRoute: typeof GuruChatSessionIdRouteImport
      parentRoute: typeof GuruRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GuruRouteChildren {
  GuruChatSessionIdRoute: typeof GuruChatSessionIdRoute
}

const GuruRouteChildren: GuruRouteChildren = {
  GuruChatSessionIdRoute: GuruChatSessionIdRoute,
}

const GuruRouteWithChildren = GuruRoute._addFileChildren(GuruRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuruRoute: GuruRouteWithChildren,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
